name: Add event
description: Add an event (e.g. workshop, training or demo) to be listed on the [DataPLANT events site](https://nfdi4plants.org/events/).
title: "[Add event]: "
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: excerpt
    attributes:
      label: Excerpt
      description: Max. 200 signs.
    validations:
      required: true
  - type: dropdown
    id: mode
    attributes:
      label: Mode
      options:
        - On-site
        - Online
        - Hybrid
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Conference
        - Hackathon
        - Webinar
        - Training
        - Meeting
    validations:
      required: true
  - type: dropdown
    id: audience
    attributes:
      label: Audience
      options:
        - Users
        - Data Stewards
        - Developers
      multiple: true
    validations:
      required: True
  - type: dropdown
    id: recurrence
    attributes:
      label: Recurrence
      options:
        - Single
        - Periodic
        - Series
      description: |
        Single = one-time event; Series = multiple-session event planned for non-consecutive days; Periodic = regularily repeating (e.g. Data Steward Circle)
    validations:
      required: true
  - type: textarea
    id: when
    attributes:
      label: When
      value: |
        # Single event
          start: 2024-10-24T09:00:00
          end: 2024-10-24T12:00:00

        # Multi event (consecutive days)

          start: 2024-10-24T09:00:00          
          end: 2024-10-25T17:00:00

        # Multi event (non-consecutive days)
        
        - 
          start: 2024-10-24T09:00:00
          end: 2024-10-24T17:00:00
        - 
          start: 2024-10-31T09:00:00
          end: 2024-10-31T17:00:00
      render: markdown
    validations:
      required: true
  - type: textarea
    id: organizer
    attributes:
      label: Organizer
      value: |
        organizer:
          name: 
          affiliation: 
          url: 
      description: |
        Details of responsible person, e.g.
        organizer:
          name: Mrs. Organize-A-Lot
          affiliation: DataPLANT
          url: https://www.nfdi4plants.org
    validations:
      required: false
  - type: textarea
    id: tutors
    attributes:
      label: Tutors
      description: List of tutors
      value: |
        - Sir Tutor-A-Lot (<a href="https://www.nfdi4plants.org">DataPLANT</a>)
        - Edna Krabappel          
    validations:
      required: false
  - type: textarea
    id: registration
    attributes:
      label: Registration
      value: |
        registration:
          url: 
          description:
          deadline:
          seats:
      description: |
        url: link to a registration form or a mailto-link (email address)
        description: add additional details to the registration
        deadline: 2024-10-12
        seats: Max. number of participants
      render: markdown
    validations:
      required: false
  - type: textarea
    id: location
    attributes:
      label: Location
      value: |
        url:
        name:
        address: 
      description: |
        url: link to hybrid meeting or directions (e.g. online map)
        name: 50 signs max.
        address: Street address and room
      render: markdown
    validations:
      required: false
  - type: textarea
    id: detail
    attributes:
      description: Use this free-text area to describe your event with more detail
      label: Detail
      value: |
        # About this event

        ...

        # Teaching Materials

        ... 
  - type: input
    id: image
    attributes:
      label: Image
      description: add an image URL here or upload an image via comment to the issue
